# Generated by Django 5.0.2 on 2024-04-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(default='english', max_length=50),
            preserve_default=False,
        ),
    ]
